name: Update Weekly DevMetrics

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

# Sets permissions of the WakaReadme to allow update Repo contents
permissions:
  contents: write
  
jobs:
  update-readme:
    name: Updated graph in README.md with new metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}